services:
  db:
    image: postgres:16
    container_name: vpn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: whitevpn
      POSTGRES_USER: whitevpn
      POSTGRES_PASS: whitevpn_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vpn_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"    # <--- ВАЖНО
      PGADMIN_DEFAULT_PASSWORD: "admin123"          # минимум 6 символов
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
